language: nix
before_script:
  - sudo mkdir /etc/nix && echo 'sandbox = true' | sudo tee /etc/nix/nix.conf
script:
  - nix-build --quiet release.nix -A build.x86_64-linux -I nixpkgs=channel:nixos-19.03
